// Templates use {{PLACEHOLDER}} markers — generateScripts substitutes them
// and asserts no `{{` remains after the pass.
//
// Notes on escaping:
// - These templates are wrapped in JS template literals. Every literal
//   backtick must be written as \` (so it doesn't terminate the literal).
// - Every literal `${...}` must be written as \${...} (so it isn't
//   interpolated). Bash and PowerShell both use ${VAR}; we keep them as
//   literals here.

export const MACOS_SH = `#!/bin/bash
# Daily incremental backup — generated by skillsafe-app.
# Mirrors the selected tools' config directories to {{DEST}} via rsync. The
# backup folder is then synced to your cloud drive by OneDrive/Dropbox/iCloud's
# own client.
set -u

MIRROR="{{DEST}}"
LOG="{{HOME}}/Library/Logs/skillsafe-backup.log"
N={{N}}
STEP=0

log() {
  local msg="[\$(date '+%Y-%m-%d %H:%M:%S')] \$*"
  echo "\$msg"
  echo "\$msg" >> "\$LOG"
}

if [ -f "\$LOG" ] && [ "\$(stat -f%z "\$LOG")" -gt 5242880 ]; then
  mv "\$LOG" "\${LOG}.old"
fi

FAILURES=0
log "=============================================="
log "skillsafe backup started"
log "=============================================="

if [ ! -d "\$(dirname "\$MIRROR")" ]; then
  log "ERROR: backup destination parent does not exist: \$MIRROR"
  exit 1
fi

{{TOOL_SECTIONS}}

[ \$FAILURES -eq 0 ] && exit 0 || exit 2
`;

export const MACOS_PLIST = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{{LABEL}}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>{{SCRIPT_PATH}}</string>
    </array>
    <key>StartCalendarInterval</key>
    {{CALENDAR_INTERVAL}}
    <key>RunAtLoad</key>
    <false/>
    <key>StandardOutPath</key>
    <string>{{HOME}}/Library/Logs/skillsafe-backup.log</string>
    <key>StandardErrorPath</key>
    <string>{{HOME}}/Library/Logs/skillsafe-backup.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
</dict>
</plist>
`;

export const MACOS_RESTORE_SH = `#!/bin/bash
# Restore from backup — generated by skillsafe-app.
# Reverses the backup script's path mappings. Default mode is a SAFE DRY RUN:
# the script scans for live files that would change and ABORTS without
# touching anything if conflicts are detected.
#
#   ./claude_restore.sh           # dry-run + report
#   ./claude_restore.sh --force   # actually restore (overlay)
#   ./claude_restore.sh --force --mirror
#                                 # also delete live files missing from backup
set -u

MIRROR="{{DEST}}"
LOG="{{HOME}}/Library/Logs/skillsafe-restore.log"
FORCE=0
DELETE_FLAG=""

for arg in "\$@"; do
  case "\$arg" in
    --force) FORCE=1 ;;
    --mirror) DELETE_FLAG="--delete" ;;
    --help|-h)
      cat <<USAGE
Usage: \$0 [--force] [--mirror]
  --force    Apply the restore. Without it, the script only reports.
  --mirror   Also remove live files not present in the backup.
USAGE
      exit 0 ;;
    *) echo "Unknown flag: \$arg" >&2; exit 64 ;;
  esac
done

log() { local m="[\$(date '+%Y-%m-%d %H:%M:%S')] \$*"; echo "\$m"; echo "\$m" >> "\$LOG"; }

if [ ! -d "\$MIRROR" ]; then
  log "ERROR: backup folder does not exist: \$MIRROR"
  exit 1
fi

log "=============================================="
log "skillsafe restore  force=\$FORCE  mirror=\${DELETE_FLAG:-(off)}"
log "=============================================="

TOTAL_CHANGES=0
FAILURES=0

# Dry-run: ask rsync what it would change. itemize-changes prefixes every
# affected entry with a 1-char code (>fcst, *deleting, cd+++++, …); we count
# those lines to decide whether the live tree is in sync with the backup.
scan() {
  local label="\$1" src="\$2" dst="\$3"
  if [ ! -e "\$src" ]; then
    log "  [skip] missing in backup: \$src"
    return 0
  fi
  local out cnt
  out=\$(rsync -ain \$DELETE_FLAG --copy-unsafe-links "\$src" "\$dst" 2>/dev/null) || return 0
  cnt=\$(printf '%s\\n' "\$out" | grep -cE '^[<>cdL*]' || true)
  if [ "\${cnt:-0}" -gt 0 ]; then
    TOTAL_CHANGES=\$((TOTAL_CHANGES+cnt))
    log "  [dry] \$label · \$cnt change(s)"
    printf '%s\\n' "\$out" | grep -E '^[<>cdL*]' | head -20 | sed 's/^/      /' >> "\$LOG"
  fi
}

apply() {
  local label="\$1" src="\$2" dst="\$3"
  [ ! -e "\$src" ] && return 0
  mkdir -p "\$dst" 2>/dev/null || true
  if rsync -a \$DELETE_FLAG --copy-unsafe-links "\$src" "\$dst"; then
    log "  [ok]  \$label"
  else
    log "  [FAIL] \$label"
    FAILURES=\$((FAILURES+1))
  fi
}

log "Phase 1: scanning backup vs live tree…"
{{SCAN_SECTIONS}}

if [ \$TOTAL_CHANGES -eq 0 ]; then
  log ""
  log "Live tree already matches the backup. Nothing to restore."
  exit 0
fi

if [ \$FORCE -eq 0 ]; then
  log ""
  log "WARNING: restoring would modify \$TOTAL_CHANGES file(s) in your live tree."
  log "         Re-run with --force to apply (or --force --mirror to also delete extras)."
  log "         Detail in: \$LOG"
  exit 2
fi

log ""
log "Phase 2: applying restore…"
{{APPLY_SECTIONS}}

[ \$FAILURES -eq 0 ] && { log "Restore complete."; exit 0; } || { log "Restore finished with \$FAILURES failure(s)."; exit 2; }
`;

export const WINDOWS_RESTORE_PS1 = `# Restore from backup — generated by skillsafe-app.
# Default is a dry-run: robocopy is invoked with /L so nothing on disk is
# touched. The script reports any folders that would receive changes and
# aborts unless -Force is passed.

[CmdletBinding()]
param(
  [switch]\$Force,
  [switch]\$Mirror
)

\$Mirror2 = "{{DEST}}"
\$LogDir2 = Join-Path \$env:LOCALAPPDATA "skillsafe-app\\Logs"
\$LogFile = Join-Path \$LogDir2 "skillsafe-restore.log"

if (-not (Test-Path \$LogDir2)) { New-Item -ItemType Directory -Force -Path \$LogDir2 | Out-Null }

if (-not (Test-Path \$Mirror2)) {
  Write-Host "ERROR: backup folder does not exist: \$Mirror2"; exit 1
}

function Write-Log([string]\$m) {
  \$line = "[\$((Get-Date).ToString('yyyy-MM-dd HH:mm:ss'))] \$m"
  Add-Content -Path \$LogFile -Value \$line; Write-Host \$line
}

\$rcFlags = @("/E","/R:2","/W:5","/NFL","/NDL","/NP")
if (\$Mirror) { \$rcFlags = @("/MIR","/R:2","/W:5","/NFL","/NDL","/NP") }

\$total = 0
\$failures = 0

function Scan([string]\$label, [string]\$src, [string]\$dst) {
  if (-not (Test-Path \$src)) { Write-Log "  [skip] missing in backup: \$src"; return }
  \$null = & robocopy \$src \$dst @rcFlags /L 2>&1
  # robocopy: 0 = synced, 1..7 = changes detected, >=8 = failure
  if (\$LASTEXITCODE -ge 1 -and \$LASTEXITCODE -lt 8) {
    \$global:total++
    Write-Log "  [dry] \$label would receive changes (code \$LASTEXITCODE)"
  }
}

function Apply([string]\$label, [string]\$src, [string]\$dst) {
  if (-not (Test-Path \$src)) { return }
  New-Item -ItemType Directory -Force -Path \$dst | Out-Null
  & robocopy \$src \$dst @rcFlags 2>&1 | Out-Null
  if (\$LASTEXITCODE -ge 8) { Write-Log "  [FAIL] \$label (\$LASTEXITCODE)"; \$global:failures++ }
  else { Write-Log "  [ok]  \$label" }
}

Write-Log "=============================================="
Write-Log "skillsafe restore  Force=\$Force  Mirror=\$Mirror"

Write-Log "Phase 1: scanning backup vs live tree..."
{{SCAN_SECTIONS}}

if (\$total -eq 0) { Write-Log "Live tree matches the backup. Nothing to restore."; exit 0 }
if (-not \$Force) {
  Write-Log "WARNING: \$total folder(s) would be modified. Re-run with -Force."
  exit 2
}

Write-Log "Phase 2: applying restore..."
{{APPLY_SECTIONS}}

if (\$failures -eq 0) { Write-Log "Restore complete."; exit 0 } else { exit 2 }
`;

export const README_MAC = `# Scheduled backup install (macOS)

This folder contains a self-contained installer for a daily backup of your
Claude Code data. The skillsafe-app emitted these files with your paths
already filled in.

## What it does

Every day at 22:00, a launchd job runs claude_backup.sh. The script mirrors
the selected tools' config directories — currently:

{{TOOL_LIST_MD}}

…to: {{DEST}}

Your cloud client (OneDrive / Dropbox / iCloud) handles upload + version
history from there.

## Install (one-time)

Open Terminal and run these three commands:

    chmod +x "{{SCRIPT_PATH}}"
    cp "{{PLIST_PATH}}" ~/Library/LaunchAgents/{{LABEL}}.plist
    launchctl bootstrap gui/\$(id -u) ~/Library/LaunchAgents/{{LABEL}}.plist

## Required permission (one-time)

macOS requires Full Disk Access for /bin/bash so the script can read
~/Library/Application Support/Claude/. Open:

System Settings → Privacy & Security → Full Disk Access → "+" → ⌘⇧G →
type /bin → select bash → enable the toggle.

## Verify

Run a one-off backup right now:

    "{{SCRIPT_PATH}}"
    tail -20 ~/Library/Logs/skillsafe-backup.log

You should see three "OK" lines.

## Uninstall

    launchctl bootout gui/\$(id -u) ~/Library/LaunchAgents/{{LABEL}}.plist
    rm ~/Library/LaunchAgents/{{LABEL}}.plist
`;

export const WINDOWS_PS1 = `# Daily incremental backup — generated by skillsafe-app.
# Uses Robocopy /MIR to mirror selected tools' config directories to a
# OneDrive/Dropbox folder. Run via Task Scheduler.

\$ErrorActionPreference = "Continue"
\$Mirror  = "{{DEST}}"
\$LogDir  = Join-Path \$env:LOCALAPPDATA "skillsafe-app\\Logs"
\$LogFile = Join-Path \$LogDir "skillsafe-backup.log"
\$N = {{N}}
\$Step = 0

if (-not (Test-Path \$LogDir)) { New-Item -ItemType Directory -Force -Path \$LogDir | Out-Null }

function Write-Log([string]\$msg) {
  \$line = "[\$((Get-Date).ToString('yyyy-MM-dd HH:mm:ss'))] \$msg"
  Add-Content -Path \$LogFile -Value \$line
  Write-Host \$line
}

if ((Test-Path \$LogFile) -and ((Get-Item \$LogFile).Length -gt 5MB)) {
  Move-Item \$LogFile "\$LogFile.old" -Force
}

\$failures = 0
Write-Log "=============================================="
Write-Log "skillsafe backup started"

if (-not (Test-Path (Split-Path \$Mirror))) {
  Write-Log "ERROR: backup destination parent does not exist"
  exit 1
}

{{TOOL_SECTIONS}}

if (\$failures -eq 0) { exit 0 } else { exit 2 }
`;

export const WINDOWS_REGISTER_PS1 = `# Register the daily backup task with Windows Task Scheduler.
# Run this PowerShell window as Administrator.

\$action    = New-ScheduledTaskAction -Execute "powershell.exe" -Argument '-WindowStyle Hidden -ExecutionPolicy Bypass -File "{{SCRIPT_PATH}}"'
\$trigger   = New-ScheduledTaskTrigger -Daily -At "22:00"
\$settings  = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable
\$principal = New-ScheduledTaskPrincipal -UserId "\$env:USERNAME" -LogonType S4U -RunLevel Limited

Register-ScheduledTask -TaskName "{{LABEL}}" -Action \$action -Trigger \$trigger -Settings \$settings -Principal \$principal -Description "skillsafe-app daily backup"
`;

export const LINUX_SH = `#!/bin/bash
# Daily incremental backup — generated by skillsafe-app.
# Mirrors the selected tools' config directories to {{DEST}} via rsync.
set -u

MIRROR="{{DEST}}"
LOG="{{LOG_PATH}}"
N={{N}}
STEP=0

mkdir -p "\$(dirname "\$LOG")" 2>/dev/null || true

log() {
  local msg="[\$(date '+%Y-%m-%d %H:%M:%S')] \$*"
  echo "\$msg"
  echo "\$msg" >> "\$LOG"
}

# GNU stat — \`stat -c%s\` reports byte size on Linux.
if [ -f "\$LOG" ] && [ "\$(stat -c%s "\$LOG" 2>/dev/null || echo 0)" -gt 5242880 ]; then
  mv "\$LOG" "\${LOG}.old"
fi

FAILURES=0
log "=============================================="
log "skillsafe backup started"
log "=============================================="

if [ ! -d "\$(dirname "\$MIRROR")" ]; then
  log "ERROR: backup destination parent does not exist: \$MIRROR"
  exit 1
fi

{{TOOL_SECTIONS}}

[ \$FAILURES -eq 0 ] && exit 0 || exit 2
`;

export const LINUX_RESTORE_SH = `#!/bin/bash
# Restore from backup — generated by skillsafe-app.
# Default mode is a SAFE DRY RUN: scan only, no changes.
#
#   ./claude_restore.sh           # dry-run + report
#   ./claude_restore.sh --force   # actually restore (overlay)
#   ./claude_restore.sh --force --mirror
set -u

MIRROR="{{DEST}}"
LOG="{{LOG_PATH_RESTORE}}"
FORCE=0
DELETE_FLAG=""

mkdir -p "\$(dirname "\$LOG")" 2>/dev/null || true

for arg in "\$@"; do
  case "\$arg" in
    --force) FORCE=1 ;;
    --mirror) DELETE_FLAG="--delete" ;;
    --help|-h)
      cat <<USAGE
Usage: \$0 [--force] [--mirror]
  --force    Apply the restore. Without it, the script only reports.
  --mirror   Also remove live files not present in the backup.
USAGE
      exit 0 ;;
    *) echo "Unknown flag: \$arg" >&2; exit 64 ;;
  esac
done

log() { local m="[\$(date '+%Y-%m-%d %H:%M:%S')] \$*"; echo "\$m"; echo "\$m" >> "\$LOG"; }

if [ ! -d "\$MIRROR" ]; then
  log "ERROR: backup folder does not exist: \$MIRROR"
  exit 1
fi

log "=============================================="
log "skillsafe restore  force=\$FORCE  mirror=\${DELETE_FLAG:-(off)}"
log "=============================================="

TOTAL_CHANGES=0
FAILURES=0

scan() {
  local label="\$1" src="\$2" dst="\$3"
  if [ ! -e "\$src" ]; then
    log "  [skip] missing in backup: \$src"
    return 0
  fi
  local out cnt
  out=\$(rsync -ain \$DELETE_FLAG --copy-unsafe-links "\$src" "\$dst" 2>/dev/null) || return 0
  cnt=\$(printf '%s\\n' "\$out" | grep -cE '^[<>cdL*]' || true)
  if [ "\${cnt:-0}" -gt 0 ]; then
    TOTAL_CHANGES=\$((TOTAL_CHANGES+cnt))
    log "  [dry] \$label · \$cnt change(s)"
    printf '%s\\n' "\$out" | grep -E '^[<>cdL*]' | head -20 | sed 's/^/      /' >> "\$LOG"
  fi
}

apply() {
  local label="\$1" src="\$2" dst="\$3"
  [ ! -e "\$src" ] && return 0
  mkdir -p "\$dst" 2>/dev/null || true
  if rsync -a \$DELETE_FLAG --copy-unsafe-links "\$src" "\$dst"; then
    log "  [ok]  \$label"
  else
    log "  [FAIL] \$label"
    FAILURES=\$((FAILURES+1))
  fi
}

log "Phase 1: scanning backup vs live tree…"
{{SCAN_SECTIONS}}

if [ \$TOTAL_CHANGES -eq 0 ]; then
  log ""
  log "Live tree already matches the backup. Nothing to restore."
  exit 0
fi

if [ \$FORCE -eq 0 ]; then
  log ""
  log "WARNING: restoring would modify \$TOTAL_CHANGES file(s) in your live tree."
  log "         Re-run with --force to apply (or --force --mirror to also delete extras)."
  log "         Detail in: \$LOG"
  exit 2
fi

log ""
log "Phase 2: applying restore…"
{{APPLY_SECTIONS}}

[ \$FAILURES -eq 0 ] && { log "Restore complete."; exit 0; } || { log "Restore finished with \$FAILURES failure(s)."; exit 2; }
`;

export const README_LINUX = `# Scheduled backup install (Linux)

This folder contains a self-contained installer for a daily backup of your
Claude Code data. The skillsafe-app emitted these files with your paths
already filled in.

## What it does

Every day at the configured time, a cron job runs claude_backup.sh. The
script mirrors the selected tools' config directories — currently:

{{TOOL_LIST_MD}}

…to: {{DEST}}

Your cloud client (Dropbox / OneDrive / etc.) handles upload + version
history from there.

## Install (one-time)

The skillsafe-app's "Install daily backup" button does this for you. To do
it manually:

    chmod +x "{{SCRIPT_PATH}}"
    ( crontab -l 2>/dev/null | grep -v '{{LABEL}}' ; \\
      echo '0 22 * * * "{{SCRIPT_PATH}}" # {{LABEL}}' ) | crontab -

## Verify

    "{{SCRIPT_PATH}}"
    tail -20 "{{LOG_PATH}}"

## Uninstall

    crontab -l 2>/dev/null | grep -v '{{LABEL}}' | crontab -
`;

export const README_WIN = `# Scheduled backup install (Windows)

This folder contains a self-contained installer for a daily backup of your
Claude Code data. The skillsafe-app emitted these files with your paths
already filled in.

## What it does

Every day at 22:00, a Task Scheduler job runs claude_backup.ps1, which uses
Robocopy to mirror the selected tools' config directories — currently:

{{TOOL_LIST_MD}}

…to: {{DEST}}

Your cloud client (OneDrive / Dropbox) handles upload + version history.

## One-time setup

1. Open PowerShell as Administrator.
2. Allow scripts to run for the current user (only needed once):

       Set-ExecutionPolicy -Scope CurrentUser RemoteSigned -Force

3. Register the daily task:

       & "{{REGISTER_SCRIPT_PATH}}"

## Verify

Run the backup once now:

    & "{{SCRIPT_PATH}}"
    Get-Content "\$env:LOCALAPPDATA\\skillsafe-app\\Logs\\skillsafe-backup.log" -Tail 20

## Uninstall

    Unregister-ScheduledTask -TaskName "{{LABEL}}" -Confirm:\$false
`;
