// Templates use {{PLACEHOLDER}} markers — generateScripts substitutes them
// and asserts no `{{` remains after the pass.
//
// Notes on escaping:
// - These templates are wrapped in JS template literals. Every literal
//   backtick must be written as \` (so it doesn't terminate the literal).
// - Every literal `${...}` must be written as \${...} (so it isn't
//   interpolated). Bash and PowerShell both use ${VAR}; we keep them as
//   literals here.

export const MACOS_SH = `#!/bin/bash
# Claude Code daily incremental backup — generated by skillsafe-app
# Mirrors ~/.claude and the Claude Desktop config to {{DEST}} via rsync. The
# backup folder is then synced to your cloud drive by OneDrive/Dropbox/iCloud's
# own client.
set -u

MIRROR="{{DEST}}"
LOG="{{HOME}}/Library/Logs/skillsafe-backup.log"

log() {
  local msg="[\$(date '+%Y-%m-%d %H:%M:%S')] \$*"
  echo "\$msg"
  echo "\$msg" >> "\$LOG"
}

if [ -f "\$LOG" ] && [ "\$(stat -f%z "\$LOG")" -gt 5242880 ]; then
  mv "\$LOG" "\${LOG}.old"
fi

FAILURES=0
log "=============================================="
log "skillsafe backup started"
log "=============================================="

if [ ! -d "\$(dirname "\$MIRROR")" ]; then
  log "ERROR: backup destination parent does not exist: \$MIRROR"
  exit 1
fi

mkdir -p "\$MIRROR/claude" "\$MIRROR/claude_desktop"

log "[1/2] Sync ~/.claude/ ..."
rsync -a --delete \\
  --exclude='.DS_Store' \\
  --exclude='cache/' \\
  --exclude='debug/' \\
  --exclude='session-env/' \\
  --exclude='shell-snapshots/' \\
  --exclude='telemetry/' \\
  --exclude='usage-data/' \\
  --exclude='statsig/' \\
  --exclude='downloads/' \\
  --exclude='paste-cache/' \\
  --exclude='ide/' \\
  --exclude='channels/' \\
  --exclude='plugins/cache/' \\
  --exclude='mcp-needs-auth-cache.json' \\
  --exclude='policy-limits.json' \\
  --exclude='stats-cache.json' \\
  --exclude='projects/-Users-*-Library-CloudStorage-*' \\
  "{{HOME}}/.claude/" "\$MIRROR/claude/"
[ \$? -eq 0 ] && log "[1/2] OK (\$(du -sh "\$MIRROR/claude" 2>/dev/null | cut -f1))" || { log "[1/2] FAILED"; FAILURES=\$((FAILURES+1)); }

log "[2/2] Sync Claude Desktop config ..."
RC=0
if [ -f "{{HOME}}/Library/Application Support/Claude/claude_desktop_config.json" ]; then
  rsync -a "{{HOME}}/Library/Application Support/Claude/claude_desktop_config.json" "\$MIRROR/claude_desktop/" || RC=\$?
fi
if [ -f "{{HOME}}/Library/Application Support/Claude/config.json" ]; then
  rsync -a "{{HOME}}/Library/Application Support/Claude/config.json" "\$MIRROR/claude_desktop/" || RC=\$?
fi
[ \$RC -eq 0 ] && log "[2/2] OK" || { log "[2/2] FAILED"; FAILURES=\$((FAILURES+1)); }

{
  echo "Last backup: \$(date '+%Y-%m-%d %H:%M:%S')"
  echo "Failures: \$FAILURES"
  du -sh "\$MIRROR"/* 2>/dev/null
} > "\$MIRROR/LAST_BACKUP.txt"

[ \$FAILURES -eq 0 ] && exit 0 || exit 2
`;

export const MACOS_PLIST = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{{LABEL}}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>{{SCRIPT_PATH}}</string>
    </array>
    <key>StartCalendarInterval</key>
    {{CALENDAR_INTERVAL}}
    <key>RunAtLoad</key>
    <false/>
    <key>StandardOutPath</key>
    <string>{{HOME}}/Library/Logs/skillsafe-backup.log</string>
    <key>StandardErrorPath</key>
    <string>{{HOME}}/Library/Logs/skillsafe-backup.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
</dict>
</plist>
`;

export const README_MAC = `# Scheduled backup install (macOS)

This folder contains a self-contained installer for a daily backup of your
Claude Code data. The skillsafe-app emitted these files with your paths
already filled in.

## What it does

Every day at 12:15, a launchd job runs claude_backup.sh. The script mirrors:

- ~/.claude/ (skills, agents, commands, projects, settings, plugins)
- ~/Library/Application Support/Claude/claude_desktop_config.json

…to: {{DEST}}

Your cloud client (OneDrive / Dropbox / iCloud) handles upload + version
history from there.

## Install (one-time)

Open Terminal and run these three commands:

    chmod +x "{{SCRIPT_PATH}}"
    cp "{{PLIST_PATH}}" ~/Library/LaunchAgents/{{LABEL}}.plist
    launchctl bootstrap gui/\$(id -u) ~/Library/LaunchAgents/{{LABEL}}.plist

## Required permission (one-time)

macOS requires Full Disk Access for /bin/bash so the script can read
~/Library/Application Support/Claude/. Open:

System Settings → Privacy & Security → Full Disk Access → "+" → ⌘⇧G →
type /bin → select bash → enable the toggle.

## Verify

Run a one-off backup right now:

    "{{SCRIPT_PATH}}"
    tail -20 ~/Library/Logs/skillsafe-backup.log

You should see three "OK" lines.

## Uninstall

    launchctl bootout gui/\$(id -u) ~/Library/LaunchAgents/{{LABEL}}.plist
    rm ~/Library/LaunchAgents/{{LABEL}}.plist
`;

export const WINDOWS_PS1 = `# Claude Code daily incremental backup — generated by skillsafe-app
# Uses Robocopy /MIR to mirror ~/.claude and Claude Desktop config to a
# OneDrive/Dropbox folder. Run via Task Scheduler.

\$ErrorActionPreference = "Continue"
\$Mirror  = "{{DEST}}"
\$LogFile = "{{HOME}}\\skillsafe-backup.log"

function Write-Log([string]\$msg) {
  \$line = "[\$((Get-Date).ToString('yyyy-MM-dd HH:mm:ss'))] \$msg"
  Add-Content -Path \$LogFile -Value \$line
  Write-Host \$line
}

if ((Test-Path \$LogFile) -and ((Get-Item \$LogFile).Length -gt 5MB)) {
  Move-Item \$LogFile "\$LogFile.old" -Force
}

\$failures = 0
Write-Log "=============================================="
Write-Log "skillsafe backup started"

if (-not (Test-Path (Split-Path \$Mirror))) {
  Write-Log "ERROR: backup destination parent does not exist"
  exit 1
}

@("\$Mirror\\claude", "\$Mirror\\claude_desktop") | ForEach-Object {
  New-Item -ItemType Directory -Force -Path \$_ | Out-Null
}

# [1/2] ~/.claude
Write-Log "[1/2] Sync .claude ..."
\$src = "{{HOME}}\\.claude"
if (Test-Path \$src) {
  \$excludeDirs = @("cache","debug","session-env","shell-snapshots","telemetry","usage-data","statsig","downloads","paste-cache","ide","channels")
  \$excludeFiles = @("mcp-needs-auth-cache.json","policy-limits.json","stats-cache.json")
  & robocopy \$src "\$Mirror\\claude" /MIR /R:2 /W:5 /NFL /NDL /NP /XD \$excludeDirs "\$src\\plugins\\cache" /XF \$excludeFiles | Out-Null
  if (\$LASTEXITCODE -lt 8) { Write-Log "[1/2] OK" } else { Write-Log "[1/2] FAILED (\$LASTEXITCODE)"; \$failures++ }
} else { Write-Log "[1/2] skipped (no .claude)" }

# [2/2] Claude Desktop config
Write-Log "[2/2] Sync Claude Desktop config ..."
\$cfg = "\$env:APPDATA\\Claude\\claude_desktop_config.json"
if (Test-Path \$cfg) { Copy-Item \$cfg "\$Mirror\\claude_desktop\\" -Force; Write-Log "[2/2] OK" }
else { Write-Log "[2/2] skipped (no config)" }

@"
Last backup: \$((Get-Date).ToString('yyyy-MM-dd HH:mm:ss'))
Failures: \$failures
"@ | Set-Content "\$Mirror\\LAST_BACKUP.txt"

if (\$failures -eq 0) { exit 0 } else { exit 2 }
`;

export const WINDOWS_REGISTER_PS1 = `# Register the daily backup task with Windows Task Scheduler.
# Run this PowerShell window as Administrator.

\$action    = New-ScheduledTaskAction -Execute "powershell.exe" -Argument '-WindowStyle Hidden -ExecutionPolicy Bypass -File "{{SCRIPT_PATH}}"'
\$trigger   = New-ScheduledTaskTrigger -Daily -At "12:15"
\$settings  = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable
\$principal = New-ScheduledTaskPrincipal -UserId "\$env:USERNAME" -LogonType S4U -RunLevel Limited

Register-ScheduledTask -TaskName "{{LABEL}}" -Action \$action -Trigger \$trigger -Settings \$settings -Principal \$principal -Description "skillsafe-app daily backup"
`;

export const README_WIN = `# Scheduled backup install (Windows)

This folder contains a self-contained installer for a daily backup of your
Claude Code data. The skillsafe-app emitted these files with your paths
already filled in.

## What it does

Every day at 12:15, a Task Scheduler job runs claude_backup.ps1, which uses
Robocopy to mirror ~/.claude and your Claude Desktop config to: {{DEST}}

Your cloud client (OneDrive / Dropbox) handles upload + version history.

## One-time setup

1. Open PowerShell as Administrator.
2. Allow scripts to run for the current user (only needed once):

       Set-ExecutionPolicy -Scope CurrentUser RemoteSigned -Force

3. Register the daily task:

       & "{{REGISTER_SCRIPT_PATH}}"

## Verify

Run the backup once now:

    & "{{SCRIPT_PATH}}"
    Get-Content "{{HOME}}\\skillsafe-backup.log" -Tail 20

## Uninstall

    Unregister-ScheduledTask -TaskName "{{LABEL}}" -Confirm:\$false
`;
